@APIURL = http://localhost:3000/api

###
POST {{APIURL}}/rides
Content-Type: application/json

{
    "location": "Torino",
    "date": "17/01/2024",
    "time": "14:30",
    "duration": "30",
    "timeUnit": "min"
}

###
DELETE {{APIURL}}/notification/1
Content-Type: application/json

###
GET {{APIURL}}/notification/
Content-Type: application/json

### LOGIN user1
POST {{APIURL}}/login HTTP/1.1
content-type: application/json

{
    "username": "david.miller@email.com",
    "password": "password1234"
}

### Still logged in
GET {{APIURL}}/login/current HTTP/1.1

### Logout
DELETE {{APIURL}}/login HTTP/1.1